// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdT23yU4jKyUolrw7bG2j_siQ0GCmueRs',
    appId: '1:950565130203:android:4e2ab24fc6e7c0948d21fe',
    messagingSenderId: '950565130203',
    projectId: 'hztproject-1e273',
    databaseURL: 'https://hztproject-1e273-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hztproject-1e273.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWcdgSXw6YRHblL-zR5rytISk8fh2dYy4',
    appId: '1:950565130203:ios:70b7e2dbccc8f21d8d21fe',
    messagingSenderId: '950565130203',
    projectId: 'hztproject-1e273',
    databaseURL: 'https://hztproject-1e273-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hztproject-1e273.appspot.com',
    iosClientId: '950565130203-b2eq2fpi1pv8mqekao6oo7v3pk44h934.apps.googleusercontent.com',
    iosBundleId: 'com.example.healtzoneV0',
  );
}
